waypoint_following:
  ros__parameters:
    use_sim_time: true
    frequency: 30

    # Topic
    goal_topic: /goal_pose

    # Frame to publish waypoint pose
    map_frame: map

    # Waypoints which represents points of the route, x, y, theta
    waypoints: [20.8, -9.5, 1., 17.7, -44.8, 1.8]

    # Flag, if true, the points start going to the topic. Start following only after starting and initializing all nodes
    start_following: false